Create User Service with Repository pattern
foggy21/ClinicWebSite pull request #3
Opened 2022-10-05 22:41 UTC by foggy21

1. Создал класс Result, отвечающий за вывод ошибки/положительного ответа. Пользователь будет получать статус код или статус код с описанием ошибки в зависимости от того, как отработал метод.
2. Создал Class Library DAL, где будут хранится интерфейсы и классы репозитория. Есть базовый интерфейс, в котором определяются основные методы работы с репозиторием. Так же создается интерфейс репозитория для работы с определенной сущностью (Если нужны дополнительные методы для работы с ней). После чего создается класс, в котором все эти методы реализуются.
3. Создал Class Library Service. С помощью интерфейсного программирования описал Use Cases в интерфейсе IUserService и реализовал его классе UserService.

2022-10-05 23:06 UTC, Vixorem requested changes
Есть код, который не нужен по заданию, но нет кода, который нужен (тесты)

2022-10-05 23:06 UTC, Vixorem commented on WebAPI/DAL/ApplicationDbContext.cs
> +    public class ApplicationDbContext : DbContext
В задании не шла речь про такое)

2022-10-05 23:06 UTC, Vixorem commented on WebAPI/DAL/Interfaces/IBaseRepository.cs
> +    public interface IBaseRepository<T>
Ну давай теперь, поясняй, почему это должно находиться в dal уровне

2022-10-05 23:06 UTC, Vixorem commented on WebAPI/Domain/Entities/StatusCode.cs
> +    public enum StatusCode
А это на какой случай?

2022-10-05 23:17 UTC, foggy21 commented on WebAPI/DAL/Interfaces/IBaseRepository.cs
> +    public interface IBaseRepository<T>
Это базовый интерфейс для работы с данными.

2022-10-05 23:20 UTC, foggy21 commented on WebAPI/Domain/Entities/StatusCode.cs
> +    public enum StatusCode
Это перечисление используется в Result.cs, чтобы понимать, с каким статусом кодом отработал метод. То есть метод отработал хорошо, тогда вернется Ok, либо же другой статус код, в зависимости от того, какую ошибку мы ожидаем.

2022-10-05 23:23 UTC, foggy21 commented on WebAPI/DAL/ApplicationDbContext.cs
> +    public class ApplicationDbContext : DbContext
Так это часть паттерна "Репозиторий", в любом случае пригодится.

2022-10-05 23:26 UTC, foggy21 commented
Тесты я сделаю. Я планировал этот таск для себя разделить на две части. В первой части делаю сам функционал, который коммичу. Во второй - пишу тесты, которые уже пойдут в другой коммит. Но если что, конечно, буду дорабатывать.

2022-10-05 23:28 UTC, Vixorem commented on WebAPI/DAL/ApplicationDbContext.cs
> +    public class ApplicationDbContext : DbContext
Entity framework это библиотека и не имеет ничего общего к паттерну

2022-10-05 23:28 UTC, Vixorem commented on WebAPI/DAL/Interfaces/IBaseRepository.cs
> +    public interface IBaseRepository<T>
А почему именно в DAL слое?

2022-10-05 23:30 UTC, Vixorem commented on WebAPI/Domain/Entities/StatusCode.cs
> +    public enum StatusCode
Что то уж сильно они httpшные)

2022-10-05 23:36 UTC, Vixorem commented
Коммитить можно скоко хош, просто тогда давай нажимать request review уже когда ты считаешь, что все готово

2022-10-05 23:41 UTC, foggy21 commented on WebAPI/DAL/Interfaces/IBaseRepository.cs
> +    public interface IBaseRepository<T>
DAL слой отвечает за доступ к данным. А этот интерфейс определяет методы, которые работают с данными.

2022-10-06 00:01 UTC, Vixorem commented on WebAPI/DAL/Interfaces/IBaseRepository.cs
> +    public interface IBaseRepository<T>
Получается, этот интерфейс будет импортить бизнес логика. Получается, теперь бизнес логика зависит от того, какой интерфейс отдает проект DAL, а если нам понадобится перейти на другое зранилище и заимпортить другой DAL, то там могут быть свои интерфейсы и мы будем бегать по всему domain проекту и менять его

А что если нам вообще надо будет на ходу решать, в зависимости от случая, в какой хранилище обращаться, мы же не сможем на ходу поменять интерфейс

Теперь высокоуровневая логика зависит от такой инфраструктурной вещи, как доступ к данным. То есть мы если щас удалим проект DAL, то у нас домен даже не скомпилируется

2022-10-09 09:42 UTC, Vixorem approved these changes

2022-10-19 04:16 UTC, merged