Create models And AppDbContext
foggy21/ClinicWebSite pull request #6
Opened 2022-11-08 10:10 UTC by foggy21

2022-11-08 10:33 UTC, Vixorem requested changes

2022-11-08 10:33 UTC, Vixorem commented on WebAPI/DAL/DataModels/AppointmentModel.cs
> +        public int? DoctorId { get; set; }
Я чет подзабыл, а нам нужно чтоб доктор и юзер могли быть нуль? Тогда будет какой то бесполезный аппойнтмент

2022-11-08 10:33 UTC, Vixorem commented on WebAPI/DAL/DataModels/DoctorModel.cs
> +        public  SpecializationModel specialization { get; }
Я вот щас задумался, может быть в докторе надо было хранить int SpecId, а не весь класс. Ну можно попробовать, но я щас задумался, удобно ли это будет

2022-11-08 10:33 UTC, Vixorem commented on WebAPI/DAL/Repositories/AppointmentRepository.cs
> +            return (IEnumerable<Appointment>)_db.Appointments.ToListAsync();
Прикиньте если у вас в таблице 50 лямов записей)

2022-11-08 10:33 UTC, Vixorem commented on WebAPI/DAL/Repositories/AppointmentRepository.cs
>          public bool CreateAppointment(Doctor doctor, DateTime date)
Прием у доктора происходить с пацикнтом, а где оный?)

2022-11-08 10:33 UTC, Vixorem commented on WebAPI/DAL/Repositories/AppointmentRepository.cs
>          public bool CreateAppointmentToAnyDoctor(Specialization specialization, DateTime date)
Вот такие штуки они уже выходят за рамки простых операций в бд. Это уже где то в логике надо решить и потом сказать репозиторю, че именно записать в бд

2022-11-11 11:59 UTC, foggy21 commented on WebAPI/DAL/DataModels/AppointmentModel.cs
> +        public int? DoctorId { get; set; }
Логично

2022-11-11 12:00 UTC, foggy21 commented on WebAPI/DAL/DataModels/DoctorModel.cs
> +        public  SpecializationModel specialization { get; }
Мне переделать это?

2022-11-11 12:00 UTC, foggy21 commented on WebAPI/DAL/Repositories/AppointmentRepository.cs
> +            return (IEnumerable<Appointment>)_db.Appointments.ToListAsync();
Ну так метод асинхронный для этого и нужен, чтобы вынести запрос в отдельный поток. Что не так?

2022-11-11 12:03 UTC, foggy21 commented on WebAPI/DAL/Repositories/AppointmentRepository.cs
> +            return (IEnumerable<Appointment>)_db.Appointments.ToListAsync();
Или надо какое-то ограниченное кол-во записей выводить, допустим, приемы, которые будут идти с текущего дня под конец недели?

2022-11-11 12:04 UTC, foggy21 commented on WebAPI/DAL/Repositories/AppointmentRepository.cs
>          public bool CreateAppointment(Doctor doctor, DateTime date)
Ну так в сущность приема записывается DoctorId и UserId

2022-11-11 12:05 UTC, foggy21 commented on WebAPI/DAL/Repositories/AppointmentRepository.cs
>          public bool CreateAppointmentToAnyDoctor(Specialization specialization, DateTime date)
Понял, переделаю

2022-11-11 12:37 UTC, Vixorem commented on WebAPI/DAL/DataModels/DoctorModel.cs
> +        public  SpecializationModel specialization { get; }
Ну пока оставьте, если окажется неудобным, то переделаем

2022-11-11 12:39 UTC, Vixorem commented on WebAPI/DAL/Repositories/AppointmentRepository.cs
> +            return (IEnumerable<Appointment>)_db.Appointments.ToListAsync();
Да, я имел ввиду, что если данных будет много, то приложение тупо не выезет по ресурсам. А тут еще и асинк, тогда оно не заработает, потому что такая операция ничего тут не запустит, так как тут нет await, но пока советую убрать астнк, чтоб не мучаться

2022-11-11 12:41 UTC, Vixorem commented on WebAPI/DAL/Repositories/AppointmentRepository.cs
>          public bool CreateAppointment(Doctor doctor, DateTime date)
Но сюда же добавляется только доктор, разве нет?

2022-11-14 10:48 UTC, foggy21 commented on WebAPI/DAL/Repositories/AppointmentRepository.cs
>          public bool CreateAppointment(Doctor doctor, DateTime date)
По моей логике, этот метод апдейтит (т.е. изменяет сам прием), там может изменится расписание/врач/пользователь, но ничего, по идее, добавляться же не должно, как по аналогии с запросом Update в СУБД.

2022-11-17 00:36 UTC, Vixorem commented on WebAPI/DAL/Repositories/AppointmentRepository.cs
>          public bool CreateAppointment(Doctor doctor, DateTime date)
Ну как то все равно не понял, даже если апдейт, то где апдейтится пользак

2022-11-17 00:37 UTC, Vixorem approved these changes

2022-12-26 11:05 UTC, merged